packages:
  - playground/**

catalog:
  deno: ^2.7.4
catalogs:
  vitest:
    vitest: ^4.0.18
    '@vitest/coverage-v8': ^4.0.18

minimumReleaseAge: 1440
minimumReleaseAgeExclude:
  - '@cloudflare/workers-types'

onlyBuiltDependencies:
  - deno
  - esbuild
  - workerd
